# Información del proyecto
sonar.projectKey=FrontPruebas
sonar.projectName=FrontPruebas
sonar.projectVersion=1.0

# Ruta al código fuente
sonar.sources=src

# Incluir archivos .js y .jsx explícitamente si es necesario (aunque normalmente no hace falta)
# sonar.inclusions=**/*.js,**/*.jsx

# Excluir archivos de prueba y node_modules correctamente
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/__tests__/**

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (ocúltalo si lo subes a un repo público)
sonar.login=sqp_b9aeb12821b59e214bdefa555682d71f945754d8
