# Proyecto SonarQube
sonar.projectKey=FrontPruebas
sonar.projectName=FrontPruebas
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src

# Excluir node_modules y tests para no analizar
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/__tests__/**,coverage/**

# Ruta al reporte de cobertura generado por Jest (lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación de archivos
sonar.sourceEncoding=UTF-8

# URL de SonarQube local
sonar.host.url=http://localhost:9000

# Token de acceso (no lo subas a repos públicos)
sonar.login=sqp_4a3b56d037325b731bbec512a42b8eb50f6ae1cf
