# Código fuente
sonar.sources=src,middlewares

# Cobertura de pruebas (generado por Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Excluir los tests como código fuente
sonar.exclusions=**/node_modules/**,test/**

# Incluir .js
sonar.inclusions=**/*.js

# Configuración general
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.projectKey=proyecto-seguro
sonar.projectName=proyecto-seguro
sonar.projectVersion=1.0

# SonarQube local
sonar.host.url=http://localhost:9000
sonar.login=sqp_bf99a57c16cd7fe59644c11fb76eeae6e7759a65