# Información general del proyecto
sonar.projectKey=BackendPruebas
sonar.projectName=BackendPruebas
sonar.projectVersion=1.0

# Carpeta del código fuente (ajústalo si tu código está en src/)
sonar.sources=src

# Excluir carpetas y archivos no relevantes
sonar.exclusions=**/node_modules/**,**/*.test.js,**/__tests__/**,coverage/**

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (NO lo publiques en GitHub)
sonar.login=sqp_220daecc049bdf00802c5ba97f3445b7a27b4cb1
