# Información del proyecto
sonar.projectKey=backend
sonar.projectName=pruebasBacked
sonar.projectVersion=1.0.0

# Definir explícitamente fuentes y pruebas para evitar duplicaciones
sonar.sources=src
sonar.tests=test

# Excluir los archivos de prueba de las fuentes
sonar.exclusions=test/**/*,node_modules/**/*,coverage/**/*

# Configuración de cobertura para Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/node_modules/**,**/test/**,**/tests/**,jest.config.js

# Codificación del código fuente
sonar.sourceEncoding=UTF-8